# Generated by Django 3.2.2 on 2021-05-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_room', to='base.room'),
        ),
    ]
