# Generated by Django 3.2.2 on 2021-05-11 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_surgery_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.room'),
        ),
    ]
