# Generated by Django 3.2.2 on 2021-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_surgery_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='doctors',
            field=models.ManyToManyField(to='base.Staff'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
