# Generated by Django 3.2.2 on 2021-05-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210510_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='base.Staff'),
        ),
    ]
