# Generated by Django 3.2.2 on 2021-05-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_surgery_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='requestedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='base.staff'),
        ),
    ]
