# Generated by Django 3.2.3 on 2021-05-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_surgery_requestedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='authCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
